ProyectoFinal/ProyectoApp/urls.py
from django.contrib import admin
from django.urls import path
from ProyectoApp import views
from django.conf import settings

app_name="ProyectoApp"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.inicio, name='inicio'),
    path('loginResponsable',views.loginResponsable),
    path('index',views.index, name='index'),
    path('votacion',views.votacion, name='votacion'),
    path('inicioMesa',views.inicioMesa, name='inicioMesa'),
]

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from ProyectoApp import views
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from ProyectoApp.views import index, agregar_Platillo, eliminar_Platillo, restar_Platillo, limpiar_Platillo, agregar_ticket, compruebaLog, registroMesa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('agregar/<int:platillos_id>/', agregar_Platillo, name="Add"),
    path('eliminar/<int:platillos_id>/', eliminar_Platillo, name="Del"),
    path('restar/<int:platillos_id>/', restar_Platillo, name="Sub"),
    path('limpiar/', limpiar_Platillo, name="CLS"),
    path('GRD/', agregar_ticket, name="GRD"),
    path('CPL/', compruebaLog, name="CPL"),
    path('RGM/', registroMesa, name="RGM"),
]
urlpatterns += staticfiles_urlpatterns()

ProyectoFinal/ProyectoApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Platillos(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.CharField(default=' ', max_length=1000)
    precio = models.PositiveSmallIntegerField()
    categoria = models.PositiveSmallIntegerField()
    imagen = models.CharField(default=' ', max_length=1000)

class Tickets(models.Model):
    id_ticket = models.PositiveSmallIntegerField()
    nombre = models.CharField(max_length=200)
    precio = models.PositiveSmallIntegerField()
    cantidad = models.PositiveSmallIntegerField()

class Responsables(models.Model):
    usuarioR = models.CharField(max_length=200)
    contraseñaR = models.CharField(max_length=200)
    codigoR = models.CharField(max_length=200)

class MesaInfo(models.Model):
    Mesa = models.CharField(max_length=200)
    NoMesa = models.CharField(max_length=200)
    Contraseña = models.CharField(max_length=200)
    Ubicacion = models.CharField(max_length=200)

ProyectoFinal/ProyectoApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class AgregaNombre(forms.Form):
	nombre = forms.CharField(label='Ingresa tu nombre', max_length=10)

class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

class FormTickets(forms.ModelForm):
	class Meta:
		model = Tickets
		fields = ['id_ticket', "nombre", "precio", "cantidad"]
		labels = {
			'id_ticket': 'id_ticket',
			'nombre': 'nombre',
			'precio': 'precio',
			'cantidad': 'cantidad',
		}

ProyectoFinal/ProyectoApp/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *
from .forms import *
from django.contrib import messages
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from ProyectoApp.Carrito import Carrito
from ProyectoApp.models import Platillos
from ProyectoApp.models import Tickets

def index(request):
    idti = Tickets.objects.all().last()
    datosMesa = MesaInfo.objects.all().last()
    entradas = Platillos.objects.filter(categoria = 1)
    principales = Platillos.objects.filter(categoria = 2)
    bebidas = Platillos.objects.filter(categoria = 3)
    postres = Platillos.objects.filter(categoria = 4)
    helados = Platillos.objects.filter(categoria = 5)
    return render(request,'index.html', {'entradas':entradas, 'principales':principales, 'bebidas':bebidas, 'postres':postres, 'helados':helados, 'idti':idti, 'datosMesa':datosMesa})

def inicioMesa(request):
    idMes = MesaInfo.objects.all().last()
    return render(request,'inicioMesa.html', {'idMes':idMes})

def registroMesa(request):
    idMes = request.POST['idMes']
    txt1 = request.POST['txt1']
    txt2 = request.POST['txt2']
    txt3 = request.POST['txt3']
    txt4 = request.POST['txt4']
    mesa = MesaInfo.objects.create(id=idMes,Mesa=txt1,NoMesa=txt2,Contraseña=txt3,Ubicacion=txt4)
    mesa.save()
    return redirect("ProyectoApp:index")

def votacion(request):
    helados = Platillos.objects.filter(categoria = 5)
    return render(request,'votacion.html',{'helados':helados})

def inicio(request):
    return render(request,'inicio.html')

def loginResponsable(request):
    return render(request,'loginResponsable.html')

def compruebaLog(request):
    uR = request.POST['userR1']
    pR = request.POST['passR1']
    if Responsables.objects.filter(usuarioR = uR).exists() and not Responsables.objects.filter(contraseñaR = pR).exists():
        messages.success(request, 'Tu contraseña no es correcta')
        return render(request,'loginResponsable.html')
    elif not Responsables.objects.filter(usuarioR = uR).exists() and Responsables.objects.filter(contraseñaR = pR).exists():
        messages.success(request, 'Tu usuario no es correcto')
        return render(request,'loginResponsable.html')
    elif not Responsables.objects.filter(usuarioR = uR).exists() and not Responsables.objects.filter(contraseñaR = pR).exists():
        messages.success(request, 'Ninguno de los campos es correcto')
        return render(request,'loginResponsable.html')
    else:
        admin = authenticate(username="123", password="123")
        login(request,admin)
        return redirect("ProyectoApp:inicioMesa")

def agregar_Platillo(request, platillos_id):
    carrito = Carrito(request)
    platillos = Platillos.objects.get(id=platillos_id)
    carrito.agregar(platillos)
    return redirect("ProyectoApp:index")

def eliminar_Platillo(request, platillos_id):
    carrito = Carrito(request)
    platillos = Platillos.objects.get(id=platillos_id)
    carrito.eliminar(platillos)
    return redirect("ProyectoApp:index")

def restar_Platillo(request, platillos_id):
    carrito = Carrito(request)
    platillos = Platillos.objects.get(id=platillos_id)
    carrito.restar(platillos)
    return redirect("ProyectoApp:index")

def limpiar_Platillo(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("ProyectoApp:index")

def agregar_ticket(request):
    arreglo = request.POST['arreglo']
    print(len(arreglo))
    arreglo = arreglo.split(",")
    print(arreglo)
    s = int(len(arreglo)/3)
    print(len(arreglo))
    arreglo = splita(arreglo, s)
    print(arreglo)
    cont = 0
    for x in range(s):
        id_ticket = request.POST['id_ticket']
        nombre = arreglo[cont][0]
        precio = arreglo[cont][1]
        cantidad = arreglo[cont][2]
        cont+=1
        ticket=Tickets.objects.create(id_ticket=id_ticket,nombre=nombre,precio=precio,cantidad=cantidad)
        ticket.save()
    return redirect("ProyectoApp:votacion")

def splita(arr, size):
    arrs = []
    cont = 0
    eli = 0
    for x in range(size):
        arrs.append([])
    for x in range(len(arr)):
        if cont == 3:
           cont = 0
           eli +=1
        arrs[eli].append(arr[x])
        cont+=1
    return arrs

ProyectoFinal/ProyectoApp/templates/carrito.html
{% load crispy_forms_tags %}
  <div class="alert alert-primary" role="alert" style="background-color: #FDFF9A;">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="row" colspan="3" class="text-center">CARRITO</th>
        </tr>
        <tr>
          <th scope="col">NOMBRE</th>
          <th scope="col">PRECIO</th>
          <th scope="col">CANTIDAD</th>
          <th scope="col">&nbsp&nbsp+&nbsp&nbsp|&nbsp&nbsp-&nbsp&nbsp</th>
        </tr>
      </thead>
      <tbody>
      {% if request.session.carrito.items %}
      {% for key, value in request.session.carrito.items %}
        <tr>
          <td>{{value.nombre}}</td>
          {{value.precio}}
          <td>{{value.precioAcumulado}}</td>
          <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{value.cantidad}}</td>
          <td>
            <a href="{% url 'Add' value.platillos_id %}" class="badge btn btn-dark badge-dark">+</a>
            <a href="{% url 'Sub' value.platillos_id %}" class="badge btn btn-dark badge-dark">-</a>
          </td>
        </tr>
      {% endfor %}
      {% else %}
      <tr>
          <td colspan="3">
              <div class="alert alert-danger text-center"> Sin Platillos </div>
          </td>
      </tr>
      {% endif %}
        <tr>
          <th scope="row">Total:</th>
          <td colspan="2">$ {{total_carrito}}</td>
        </tr>
      </tbody>
    </table>
    <hr>
    <div class="row text-center">
        <div class="col-14"><a href="{% url 'CLS' %}" class="btn btn-danger">Limpiar</a></div>
    </div>

    </div>
        <script>array = []</script>
        <form action="{% url 'GRD' %}" method="POST">{% csrf_token %}
            {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}

                <input type="hidden" id="id_ticket" name="id_ticket" value="{{idti.id|add:1}}"/>
                <input type="hidden" id="nombre" name="nombre" value="{{value.nombre}}"/>
                <input type="hidden" id="precio" name="precio" value="{{total_carrito}}"/>
                <input type="hidden" id="cantidad" name="cantidad" value="{{value.cantidad}}"/>
                <script>
                  nom = '{{value.nombre}}'
                  pre = '{{value.precioAcumulado}}'
                  can = '{{value.cantidad}}'
                  plat = [nom,pre,can]
                  array.push(plat);
                </script>

            {% endfor %}
            {% endif %}
                <input type="hidden" id="arreglo" name="arreglo" />
                <script>
                  // document.write(array);
                  document.getElementById("arreglo").value = array;
                </script>
          <div class="row text-center">
          <button type="submit" class="btn btn-success">Enviar a la cocina</button>
          </div>
          </form>

ProyectoFinal/ProyectoApp/templates/htmls backap/bebidas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>50amigos</title>
</head>
<body>
    <header class="inicio">
        <div class="sombra">

            <a href="#" class="carrito">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-shopping-cart" width="72" height="72" viewBox="0 0 24 24" stroke-width="1.5" stroke="#b7950b" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                <path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                <path d="M17 17h-11v-14h-2" />
                <path d="M6 5l14 1l-1 7h-13" />
              </svg>
            </a>

            <div class="barra">
                <div class="logo">
                    <a href="index.html">50<span class="logo-especial">Amigos</span></a>
                </div>
    
                <div class="categorias">
                    <a class="categoria" href="entradas.html">Entradas</a>
                    <a class="categoria" href="platos_principales.html">Platos principales</a>
                    <a class="categoria" href="bebidas.html">Bebidas</a>
                    <a class="categoria" href="postres.html">Postres</a>
                    <a class="categoria" href="helados.html">Helados</a>
                </div>
            </div>
        </div>
    </header>

    <div class="mas-pedido">
        <h2 id="titulo-mas-pedido">Nuestras Bebidas</h2>

        <div class="entradas-mas-pedidas">
            
            <div class="cards-entradas">

                <div class="entrada">
                    <img class="imagen-platillo" src="img/bebida1.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Agua de limón</p>
                    <p class="descripcion-platillo">Refrescante agua de limón acompañada con rodajas de limón fresco y recien cortado,
                         y hojas de hierba buenas.</p>
                    <p class="precio-platillo">$35</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/bebida2.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Té negro frio</p>
                    <p class="descripcion-platillo">Té negro acompañado con rodajas de limón fresco recien cortado, acompañado de hielo para darle un toque 
                        frio.
                    </p>
                    <p class="precio-platillo">$40</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/bebida3.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Frappé Oreo</p>
                    <p class="descripcion-platillo">Frappé sabor galleta Oreo, acompañado con trozos de galleta oreo y con un toque de chocolate liquido y un poco de café.</p>
                    <p class="precio-platillo">$60</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/bebida4.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Fresada</p>
                    <p class="descripcion-platillo">Agua de fresa con agua mineral, hielo, un toque de tequila con trozos de fresa y hierba buena, vaso de (83ml)</p>
                    <p class="precio-platillo">$80</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/bebida5.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Frappé Matcha</p>
                    <p class="descripcion-platillo">Frappé sabor Té Matcha, espolvoreado con té verde matcha y acompañado con chantilly clasico para un sabor dulce.</p>
                    <p class="precio-platillo">$65</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/bebida6.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Café Americano</p>
                    <p class="descripcion-platillo">Café Americano tradicional con nuestro grano recien tostado y preparado para sevir (Puedes pedir que rellenen tu tasa cuantas veces desees)</p>
                    <p class="precio-platillo">$30</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>



            </div>

            
        </div>
    </div>


    <footer class="footer">
        <div class="barra">
            <div class="logo-footer">
                <a href="index.html">50<span class="logo-especial">Amigos</span></a>
            </div>

            <div class="categorias-footer">
                <a class="categoria" href="entradas.html">Entradas</a>
                <a class="categoria" href="platos_principales.html">Platos principales</a>
                <a class="categoria" href="bebidas.html">Bebidas</a>
                <a class="categoria" href="postres.html">Postres</a>
                <a class="categoria" href="helados.html">Helados</a>
            </div>
        </div>
    </footer>
</body>
</html>

ProyectoFinal/ProyectoApp/templates/htmls backap/entradas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>50amigos</title>
</head>
<body>
    <header class="inicio">
        <div class="sombra">

            <a href="#" class="carrito">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-shopping-cart" width="72" height="72" viewBox="0 0 24 24" stroke-width="1.5" stroke="#b7950b" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                <path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                <path d="M17 17h-11v-14h-2" />
                <path d="M6 5l14 1l-1 7h-13" />
              </svg>
            </a>

            <div class="barra">
                <div class="logo">
                    <a href="index.html">50<span class="logo-especial">Amigos</span></a>
                </div>
    
                <div class="categorias">
                    <a class="categoria" href="entradas.html">Entradas</a>
                    <a class="categoria" href="platos_principales.html">Platos principales</a>
                    <a class="categoria" href="bebidas.html">Bebidas</a>
                    <a class="categoria" href="postres.html">Postres</a>
                    <a class="categoria" href="helados.html">Helados</a>
                </div>
            </div>

        </div>
    </header>

    <div class="mas-pedido">
        <h2 id="titulo-mas-pedido">Nuestra entradas</h2>

        <div class="entradas-mas-pedidas">
            
            <div class="cards-entradas">

                <div class="entrada">
                    <img class="imagen-platillo" src="img/entrada1.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Pancakes</p>
                    <p class="descripcion-platillo">Nuestros deliciosos pancakes tradicionales estilo americano compañados con frutos rojos, con maple o mermelada de tu preferencia.</p>
                    <p class="precio-platillo">$60</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/entrada2.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Papas 50Amigos</p>
                    <p class="descripcion-platillo">Nuestras papas a la francesa estan acompañadas con cebolla caramelizada, tocino, queso y aderezo especial de la casa.</p>
                    <p class="precio-platillo">$80</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/entrada3.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Sopa de crema</p>
                    <p class="descripcion-platillo">Nuestra sopa de crema de verduras tradicional esta acompañada de pequeños trozos de pan tostado y hierbas finas.</p>
                    <p class="precio-platillo">$30</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/entrada4.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Rollos de queso</p>
                    <p class="descripcion-platillo">Deliciosos rollos de queso empanizados con pan molido y galletas Maria, acompañados con un frasco de salsa ketchup.</p>
                    <p class="precio-platillo">$30</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/entrada5.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Galletas saladas</p>
                    <p class="descripcion-platillo">Disfruta de nuestras galletas saldas preparadas con hierbas finas estilo italiano y con rodajas de lima para un sabor semi dulce.</p>
                    <p class="precio-platillo">$25</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>

                <div class="entrada">
                    <img class="imagen-platillo" src="img/entrada6.jpg" alt="imagen de hot cakes">
                    <p class="nombre-platillo">Rollos de pepino</p>
                    <p class="descripcion-platillo">Rollos envueltos en tortilla de arina suabe, rellenos con trozos de pepino freso y recien cortado, acompañado por queso philadelphia.</p>
                    <p class="precio-platillo">$35</p>

                    <div class="pedido">
                        <button class="boton-ordenar">Ordenar</button>
                        <input type="number" min="1" value="1" class="cantidad-ordenada">
                    </div>
                </div>


            </div>

            
        </div>

    </div>


    <footer class="footer">
        <div class="barra">
            <div class="logo-footer">
                <a href="index.html">50<span class="logo-especial">Amigos</span></a>
            </div>

            <div class="categorias-footer">
                <a class="categoria" href="entradas.html">Entradas</a>
                <a class="categoria" href="platos_principales.html">Platos principales</a>
                <a class="categoria" href="bebidas.html">Bebidas</a>
                <a class="categoria" href="postres.html">Postres</a>
                <a class="categoria" href="helados.html">Helados</a>
            </div>
        </div>
    </footer>
</body>
</html>

ProyectoFinal/ProyectoApp/templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/style.css'%}" rel="stylesheet"/>
</head>
<body>
    <div class="indexi">
     <div class="cuadro">
      <p><p>   
      <a class="botonind" href="/admin"><button type="submit" class="botonind">Iniciar Sesión como Administrador</button></a>
      <br><br><br><br>
      <a class="botonind" href="/loginResponsable"><button type="submit" class="botonind">Iniciar Sesión como Responsable de Tablets</button></a>
      </p></p>
     </div>
    </div>

</body>
</html>

ProyectoFinal/ProyectoApp/templates/votacion.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/styles.css'%}" rel="stylesheet"/>
    <link href="{% static 'css/style.css'%}" rel="stylesheet"/>
    <title>50amigos</title>
</head>
<body class="body-helados">

    <header class="header-helados">
        <div class="barra">
            <div class="logo logo-helados">
                <a href="{% url 'ProyectoApp:index' %}">50<span class="logo-especial-helados">Amigos</span></a>
            </div>
        </div>
    </header>

    <div class="votacion">

        <label for="nombre" class="label-votacion">Nombre</label>
        <input type="text" placeholder="Tu nombre:" id="nombre">

        <label for="sabores" class="label-votacion">Sabor de helado</label>
        <select name="" id="sabores">
            <option value="" class="opcion-sabor">-- Seleccionar --</option>
            {% for helado in helados %}
            <option value="{{helado.nombre}}" class="opcion-sabor">{{helado.nombre}}</option>
            {% endfor %}
        </select>

        <button id="boton_votar">Agregar</button>
    </div>

    <div class="datos">
        
    </div>


    <button id="agregar">+</button>

    <button id="boton_terminar_votacion">Terminar votación</button>

    

    <script>


        const divi = document.querySelector(".datos");
        var div_votar = document.querySelector(".votacion");
        var boton_agregar = document.querySelector("#agregar");
        var boton = document.querySelector("#boton_votar");
        var boton_terminar = document.querySelector("#boton_terminar_votacion");
        var nombre_votante = document.querySelector("#nombre");
        var selector = document.querySelector("select"); 
        var opciones = document.querySelectorAll("option");
        var arreglo = [];
        var arreglo_cantidad = [];
        var verdad = 0;

        for (let index = 1; index < opciones.length; index++) {
            arreglo_cantidad.push(0);
            
        }

        function ventanaEmergente() {
            div_votar.style.display = "block";
        }

        function cambiar() {
            if(nombre_votante.value == "" || selector.value == "") {
                window.alert("Rellene todos los campos");
            } else {
                for (let index = 0; index < arreglo_cantidad.length; index++) {
                    if(selector.value == opciones[index + 1].value) {
                        window.alert("Votaste por el sabor " + selector.value);
                        arreglo_cantidad[index] = arreglo_cantidad[index] + 1;
                        var p = document.createElement("p");
                        var pTexto = document.createTextNode("Nombre: " + nombre_votante.value);
                        p.appendChild(pTexto);
                        divi.appendChild(p);

                        p = document.createElement("p");
                        pTexto = document.createTextNode("Sabor sleccionado: " + selector.value);
                        p.appendChild(pTexto);
                        divi.appendChild(p);

                        div_votar.style.display = "none";
                        selector.value = "";
                        nombre_votante.value = "";
                    }
                
                }
            }

        
            for (let index = 0; index < arreglo_cantidad.length; index++) {
                console.log(arreglo_cantidad[index]);
            
            }

        
        
        }

        function calcularGanador() {

            for (let index = 0; index < arreglo_cantidad.length; index++) {
                verdad = 0;
                for (let i = 0 ; i < arreglo_cantidad.length; i++) {
                    if(arreglo_cantidad[index] >= arreglo_cantidad[i]){
                        verdad += 1;
                    }
                    
                }

                if (verdad == arreglo_cantidad.length) {
                    window.alert("Ganó el sabor " + opciones[index+1].value);
                    window.location = '{% url 'ProyectoApp:inicio' %}';
                    break;
                }
                
            }

        }

        boton.onclick = cambiar;

        boton_terminar.onclick = calcularGanador;

        boton_agregar.onclick = ventanaEmergente;

    </script>
</body>
</html>